### ISSUE TITLE
Need installation docs

### ISSUE THREAD

**Issue by mkroutikov** [ichuang/tflearn_seq2seq#1]
Please add "Installation" section to the README.md

1. Requires TF 0.10 or better (does not work with TF 0.9)

2. Requires TFLEARN installed from github (PIP repository has version 0.2.1 that does not work with TF 0.10)

3. "pip install hd5py" to avoid runtime wanring: "hdf5 not supported (please install/reinstall h5py)"

After ironing out these wrinkles, it works as expected. Thank you!

**Comment by ichuang** [comment]
Done, thanks.
